name = bloodmoon
title = Blood Moon
description = Random blood moon events that turn the sky red, double zombie damage and speed, and increase spawn rates.
author = shixian
min_minetest_version = 5.6.0
